### ISSUE TITLE
failed to show friends list, load messages, check group info, change settings on windows

### ISSUE THREAD

**Issue by xxm849** [MixinNetwork/desktop-app#1114]
### Step 2: Describe your environment

  * Device: Windows 10 Pro
  * OS version:  21H1 19043.1081
  * App version: v0.12.0 and HEAD
  
### Step 3: Describe the problem:

- The left panel is empty, none of friends or chats are shown
- in debug->network, friends&albums requests and wss connection all succeeded, I can see base64-encoded up/down-stream websocket messages.
- profile/settings does not respond to click
- Search works.. means friends response is stored locally somewhere?
- But clicking search result(contact or group) does not always bring chat
- In chat window, contact info and other options do not respond to click as well.

#### Steps to reproduce:

  1. Download v0.12.0 or build using current [HEAD](https://github.com/MixinNetwork/desktop-app/commit/393b50bcbc56a6773bd41a4c7509a3baed1eee19) (`yarn electron:build --win portable`)
  2. Run mixin.exe and login.
   
#### Expected Results:

Work like mobile or macos version.

**Comment by jadeydi** [comment]
The project has stopped, it is rewriting with flutter, and will release recently.

**Comment by xxm849** [comment]
thanks. i assume flutter version is not open sourced yet?

**Comment by jadeydi** [comment]
Yeah, it will open-source soon
