### ISSUE TITLE
notification number incorrect

### ISSUE THREAD

**Issue by jadeydi** [MixinNetwork/desktop-app#576]
I clear up all the unread messages, but the notification number doesn't disappear.

<img width="334" alt="Screen Shot 2020-05-26 at 10 29 17" src="https://user-images.githubusercontent.com/416989/82854788-0e994000-9f3c-11ea-85ca-90873b01090d.png">

**Comment by isdot** [comment]
I don't seem to reproduce the problem. Can you try to send a message to yourself with another account and try if num has changed?

**Comment by isdot** [comment]
Wait...master or v0.9.6?

**Comment by jadeydi** [comment]
Version 0.9.6 (0.9.6), the number becomes to 2 after receive a new message.

**Comment by isdot** [comment]
Received, I will try, thanks a lot

**Comment by isdot** [comment]
It seems like because there is a conversation that is not displayed because of the bug of the unknown message, you can open the console to confirm.
If it is indeed the problem, the next version of this problem will be gone.

**Comment by jadeydi** [comment]
I found the conversation, Tron group and the notification number is correct now.

**Comment by isdot** [comment]
👍

**Comment by isdot** [comment]
https://github.com/MixinNetwork/desktop-app/pull/573
